/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package photoelectric_effect;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class InputQuestion extends JFrame{
    
    int count=0; //starts with question zero
    int dcount=3;
    QuestionSection QS = new QuestionSection();
    ArrayList<String> Q = new ArrayList<>();
    ArrayList<String> CA = new ArrayList<>();
    ArrayList<String> A = new ArrayList<>();
    ArrayList<String> formAnswers = new ArrayList<>();
    
    public InputQuestion() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblQuestion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaQuestion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        correctAnswer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dummy1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dummy2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dummy3 = new javax.swing.JTextField();
        helpBtn = new javax.swing.JButton();
        CloseWindowBtn = new javax.swing.JButton();
        nextQuestionBtn = new javax.swing.JButton();
        saveCurrentQuestionBtn = new javax.swing.JButton();
        previousQuestionBtn = new javax.swing.JButton();
        lastQuestionBtn = new javax.swing.JButton();
        firstQuestionBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Question Input Form");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Question input/Edit form");

        lblQuestion.setText("Question 1:");

        txtAreaQuestion.setColumns(20);
        txtAreaQuestion.setLineWrap(true);
        txtAreaQuestion.setRows(5);
        txtAreaQuestion.setText("What is the threshold frequency of a metal?");
        txtAreaQuestion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtAreaQuestion);

        jLabel3.setText("Correct answer for the question above:");

        correctAnswer.setText("It is the minimum frequency of light which will cause photoelectron emission");
        correctAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctAnswerActionPerformed(evt);
            }
        });

        jLabel4.setText("Dummy answer number 1:");

        dummy1.setText("It is the intensity of light shining on the metal surface");
        dummy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dummy1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Dummy answer number 2:");

        dummy2.setText("It is the number of photoelectrons which will be emitted");
        dummy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dummy2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Dummy answer number 3:");

        dummy3.setText("It is the maximum wavelength of photons which will release photoelectrons");
        dummy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dummy3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dummy3)
                    .addComponent(dummy1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(correctAnswer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(dummy2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 317, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correctAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dummy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dummy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dummy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        helpBtn.setText("Help");
        helpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBtnActionPerformed(evt);
            }
        });

        CloseWindowBtn.setText("Close window");
        CloseWindowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseWindowBtnActionPerformed(evt);
            }
        });

        nextQuestionBtn.setText("Next");
        nextQuestionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextQuestionBtnActionPerformed(evt);
            }
        });

        saveCurrentQuestionBtn.setText("Save Question");
        saveCurrentQuestionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCurrentQuestionBtnActionPerformed(evt);
            }
        });

        previousQuestionBtn.setText("Previous");
        previousQuestionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousQuestionBtnActionPerformed(evt);
            }
        });

        lastQuestionBtn.setText("Last");
        lastQuestionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastQuestionBtnActionPerformed(evt);
            }
        });

        firstQuestionBtn.setText("First");
        firstQuestionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstQuestionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CloseWindowBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(helpBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(firstQuestionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previousQuestionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveCurrentQuestionBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextQuestionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastQuestionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(helpBtn)
                        .addComponent(CloseWindowBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextQuestionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveCurrentQuestionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previousQuestionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastQuestionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstQuestionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void correctAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correctAnswerActionPerformed

    private void dummy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dummy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dummy1ActionPerformed

    private void dummy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dummy2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dummy2ActionPerformed

    private void dummy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dummy3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dummy3ActionPerformed

    private void CloseWindowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseWindowBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_CloseWindowBtnActionPerformed

    private void nextQuestionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextQuestionBtnActionPerformed
        Q=QS.returnQuestions();
        CA=QS.returnCorAnswers();
        A=QS.returnAnswers();
        if (count< Q.size()){
            count++;
            if (count==Q.size()){
                //append question
                lblQuestion.setText((count+1) + ".");
                txtAreaQuestion.setText("Enter new question here");
                correctAnswer.setText("Enter correct answer");
                dummy1.setText("Enter dummy answer 1");
                dummy2.setText("Enter dummy answer 2");
                dummy3.setText("Enter dummy answer 3");
            }
            else{
                //setting question and answers on form
                lblQuestion.setText((count+1) + ".");
                txtAreaQuestion.setText((String)Q.get(count));
                correctAnswer.setText((String)(String)CA.get(count));
                dummy1.setText((String)(String)A.get(dcount));
                dcount=dcount+1;
                dummy2.setText((String)(String)A.get(dcount));
                dcount=dcount+1;
                dummy3.setText((String)(String)A.get(dcount));
                dcount=dcount+1;
            }
        }
    }//GEN-LAST:event_nextQuestionBtnActionPerformed

    private void saveCurrentQuestionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCurrentQuestionBtnActionPerformed
        Q=QS.returnQuestions();
        CA=QS.returnCorAnswers();
        A=QS.returnAnswers();
        if ("".equals(dummy1.getText()) || "".equals(dummy2.getText()) || "".equals(dummy3.getText()) || "".equals(correctAnswer.getText())){
            JOptionPane.showMessageDialog(rootPane, "Please fill in all the blanks");
        }
        else{
            Q.add(txtAreaQuestion.getText());
            CA.add(correctAnswer.getText());
            A.add(dummy1.getText());
            A.add(dummy2.getText());
            A.add(dummy3.getText());
            QS.WriteToFiles(Q, CA, A);
            JOptionPane.showMessageDialog(rootPane, "Successfully saved to file");
        }
    }//GEN-LAST:event_saveCurrentQuestionBtnActionPerformed

    private void previousQuestionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousQuestionBtnActionPerformed
        Q=QS.returnQuestions();
        CA=QS.returnCorAnswers();
        A=QS.returnAnswers();
        if (count<=0){
        }
        else if (count==Q.size()){
            count--;
            lblQuestion.setText((count+1) + ".");
            txtAreaQuestion.setText((String)Q.get(count));
            correctAnswer.setText((String)(String)CA.get(count));
            dcount=dcount-3;
            dummy1.setText((String)(String)A.get(dcount));
            dcount=dcount+1;
            dummy2.setText((String)(String)A.get(dcount));
            dcount=dcount+1;
            dummy3.setText((String)(String)A.get(dcount));
            dcount=dcount+1;
        }
        else{
            count--;
            lblQuestion.setText((count+1) + ".");
            txtAreaQuestion.setText((String)Q.get(count));
            correctAnswer.setText((String)(String)CA.get(count));
            dcount=dcount-6;
            dummy1.setText((String)(String)A.get(dcount));
            dcount=dcount+1;
            dummy2.setText((String)(String)A.get(dcount));
            dcount=dcount+1;
            dummy3.setText((String)(String)A.get(dcount));
            dcount=dcount+1;
        }
        
    }//GEN-LAST:event_previousQuestionBtnActionPerformed

    private void lastQuestionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastQuestionBtnActionPerformed
        Q=QS.returnQuestions();
        CA=QS.returnCorAnswers();
        A=QS.returnAnswers();
        count=Q.size()-1;
        dcount=(Q.size()*3)-3;
        lblQuestion.setText((Q.size()) + ".");
            txtAreaQuestion.setText((String)Q.get(count));
            correctAnswer.setText((String)(String)CA.get(count));
            dummy1.setText((String)(String)A.get(dcount));
            dcount=dcount+1;
            dummy2.setText((String)(String)A.get(dcount));
            dcount=dcount+1;
            dummy3.setText((String)(String)A.get(dcount));
            dcount=dcount+1;
    }//GEN-LAST:event_lastQuestionBtnActionPerformed

    private void firstQuestionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstQuestionBtnActionPerformed
        Q=QS.returnQuestions();
        CA=QS.returnCorAnswers();
        A=QS.returnAnswers();
        count=0;
        dcount=0;
        lblQuestion.setText(1 + ".");
            txtAreaQuestion.setText((String)Q.get(count));
            correctAnswer.setText((String)(String)CA.get(count));
            dummy1.setText((String)(String)A.get(dcount));
            dcount=dcount+1;
            dummy2.setText((String)(String)A.get(dcount));
            dcount=dcount+1;
            dummy3.setText((String)(String)A.get(dcount));
            dcount=dcount+1;
    }//GEN-LAST:event_firstQuestionBtnActionPerformed

    private void helpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBtnActionPerformed
        HelpForm help = new HelpForm();
        help.setVisible(true);
    }//GEN-LAST:event_helpBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseWindowBtn;
    private javax.swing.JTextField correctAnswer;
    private javax.swing.JTextField dummy1;
    private javax.swing.JTextField dummy2;
    private javax.swing.JTextField dummy3;
    private javax.swing.JButton firstQuestionBtn;
    private javax.swing.JButton helpBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lastQuestionBtn;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JButton nextQuestionBtn;
    private javax.swing.JButton previousQuestionBtn;
    private javax.swing.JButton saveCurrentQuestionBtn;
    private javax.swing.JTextArea txtAreaQuestion;
    // End of variables declaration//GEN-END:variables
}
