/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package photoelectric_effect;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
public class QuestionAnswering extends javax.swing.JFrame {

    int count=0; //starts with question zero
    int dcount=3;
    QuestionSection QS = new QuestionSection();
    ArrayList<String> Q = new ArrayList<>();
    ArrayList<String> CA = new ArrayList<>();
    ArrayList<String> A = new ArrayList<>();
    ArrayList<String> formAnswers = new ArrayList<>();
    
    public QuestionAnswering() {
        initComponents();
        groupButton();
    }
    
    private void groupButton(){
        ButtonGroup bg1 = new ButtonGroup();
                bg1.add(answer1);
                bg1.add(answer2);
                bg1.add(answer3);
                bg1.add(answer4);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaQuestion = new javax.swing.JTextArea();
        answer1 = new javax.swing.JRadioButton();
        answer2 = new javax.swing.JRadioButton();
        answer3 = new javax.swing.JRadioButton();
        answer4 = new javax.swing.JRadioButton();
        btnCheck = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        settingsBtn = new javax.swing.JButton();
        helpBtn = new javax.swing.JButton();
        lblQuestion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Questions section");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Photoelectric effect questions");

        jScrollPane2.setBorder(null);

        txtAreaQuestion.setEditable(false);
        txtAreaQuestion.setBackground(new java.awt.Color(240, 240, 240));
        txtAreaQuestion.setColumns(20);
        txtAreaQuestion.setLineWrap(true);
        txtAreaQuestion.setRows(5);
        txtAreaQuestion.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.");
        txtAreaQuestion.setWrapStyleWord(true);
        txtAreaQuestion.setOpaque(false);
        jScrollPane2.setViewportView(txtAreaQuestion);

        answer1.setText("This is answer number 1");
        answer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1ActionPerformed(evt);
            }
        });

        answer2.setText("This is answer number 2");

        answer3.setText("First Answer");

        answer4.setText("This is answer number 4");

        btnCheck.setText("Check Answer");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        btnPrevious.setText("Previous question");
        btnPrevious.setMaximumSize(new java.awt.Dimension(59, 23));
        btnPrevious.setMinimumSize(new java.awt.Dimension(59, 23));
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText("Next question");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        settingsBtn.setText("Settings");
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });

        helpBtn.setText("Help");
        helpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBtnActionPerformed(evt);
            }
        });

        lblQuestion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuestion.setText("1.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(settingsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(helpBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(answer1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                            .addComponent(answer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(answer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(answer4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(settingsBtn)
                        .addComponent(helpBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuestion)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(answer1)
                .addGap(33, 33, 33)
                .addComponent(answer2)
                .addGap(33, 33, 33)
                .addComponent(answer3)
                .addGap(33, 33, 33)
                .addComponent(answer4)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer1ActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        CA=QS.returnCorAnswers();
        if (answer1.isSelected() || answer2.isSelected() || answer3.isSelected() || answer4.isSelected()){
            if (count==0){
                if (answer3.isSelected()){
                    JOptionPane.showMessageDialog(rootPane, "Correct!");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Incorrect!");
                }
            }
            else{
                String selectedtxt=null;
                if(answer1.isSelected()){
                    selectedtxt = (String)answer1.getText();
                }
                if(answer2.isSelected()){
                    selectedtxt = (String)answer2.getText();
                }
                if(answer3.isSelected()){
                    selectedtxt = (String)answer3.getText();
                }
                if(answer4.isSelected()){
                    selectedtxt = (String)answer4.getText();
                }
                if (selectedtxt.equals((String)CA.get(count))){
                    JOptionPane.showMessageDialog(rootPane, "Correct!");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Incorrect!");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Please choose an answer");
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        Q=QS.returnQuestions();
        CA=QS.returnCorAnswers();
        A=QS.returnAnswers();
        if (count< Q.size()-1){
            count++;
            //setting question and answers on form
            lblQuestion.setText((count+1) + ".");
            txtAreaQuestion.setText((String)Q.get(count));
            if (formAnswers!=null){
                formAnswers.clear();
            }
            formAnswers.add((String)CA.get(count));
            for (int i=0; i<3;i++){
                formAnswers.add((String)A.get(dcount));
                dcount=dcount+1;
            }
            for (int i=0;formAnswers.isEmpty()!=true;i++){//random answer selector
                Random rand = new Random();
                int RNum =rand.nextInt(formAnswers.size());
                switch(i){
                    case 0:
                        answer1.setText(formAnswers.get(RNum)); break;
                    case 1:
                        answer2.setText(formAnswers.get(RNum)); break;
                    case 2:
                        answer3.setText(formAnswers.get(RNum)); break;
                    case 3:
                        answer4.setText(formAnswers.get(RNum)); break;
                }
                formAnswers.remove(RNum);
            }
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        Q=QS.returnQuestions();
        CA=QS.returnCorAnswers();
        A=QS.returnAnswers();
        if (count==0){
        }
        else{
            count--;
            lblQuestion.setText((count+1) + ".");
            txtAreaQuestion.setText((String)Q.get(count));
            if (formAnswers!=null){
                formAnswers.clear();
            }
            dcount=dcount-6;
            formAnswers.add((String)CA.get(count));
            for (int i=0; i<3;i++){
                formAnswers.add((String)A.get(dcount));
                dcount=dcount+1;
            }
            if (count==0){
                dcount=dcount-3;
                answer1.setText((String)(String)A.get(dcount));
                dcount=dcount+1;
                answer2.setText((String)(String)A.get(dcount));
                dcount=dcount+1;
                answer3.setText((String)(String)CA.get(count));
                answer4.setText((String)(String)A.get(dcount));
                dcount=dcount+1;
            }
            else{
                for (int i=0;formAnswers.isEmpty()!=true;i++){ //random answer selector
                Random rand = new Random();
                int RNum =rand.nextInt(formAnswers.size());
                switch(i){
                    case 0:
                        answer1.setText(formAnswers.get(RNum)); break;
                    case 1:
                        answer2.setText(formAnswers.get(RNum)); break;
                    case 2:
                        answer3.setText(formAnswers.get(RNum)); break;
                    case 3:
                        answer4.setText(formAnswers.get(RNum)); break;
                }
                formAnswers.remove(RNum);
                }
            }
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void helpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBtnActionPerformed
        HelpForm help = new HelpForm();
        help.setVisible(true);
    }//GEN-LAST:event_helpBtnActionPerformed

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        SettingsLogInForm SetForm = new SettingsLogInForm();
        SetForm.setVisible(true);
    }//GEN-LAST:event_settingsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionAnswering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionAnswering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionAnswering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionAnswering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionAnswering().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton answer1;
    private javax.swing.JRadioButton answer2;
    private javax.swing.JRadioButton answer3;
    private javax.swing.JRadioButton answer4;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton helpBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JButton settingsBtn;
    private javax.swing.JTextArea txtAreaQuestion;
    // End of variables declaration//GEN-END:variables
}
