/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package photoelectric_effect;

import java.awt.Color;
import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;

/**
 *
 * @author Owner
 */
public class Simul2 extends javax.swing.JFrame {

    public String Metal;
    float phiMeV;
    double phiJoules;
    int HfMeV;
    int HfJoules;
    int Intensity;
    String DisplayJ; //display Joules values
    String DisplayM; //Display MeV values
    String material;
    
    int ERed=46;
    int EGreen=0;
    int EBlue=184;
    
    int PanRed=82;
    int PanGreen=82;
    int PanBlue=82;
    
    int PhoRed=199;
    int PhoBlue=0;
    int PhoGreen=99;
    
    int x=100;
    int y=100;
    int xv=1;
    int yv=1;
    int minx=0;
    int miny=0;
    int maxx=585;
    int maxy=550;
    
    int px=10;
    int py=100;
    
    public Simul2() {
        initComponents();
        groupBtnJM();
    }
    
    private void groupBtnJM(){
        ButtonGroup bg1 = new ButtonGroup();
        bg1.add(radioBtnJoules);
        bg1.add(radioBtnMeV);
    }
    
    String ChooseMetalString() {
        material = (String)comboPhi.getSelectedItem();
        Metal = material;
        return Metal;
    }    
    
    @Override
    public void paint (Graphics g){
        super.paint(g);
        
        Color MyColor = new Color(ERed, EGreen, EBlue);
        Color Panel = new Color(PanRed,PanGreen,PanBlue);
        Color Photon = new Color(PhoRed,PhoBlue,PhoGreen);
        
        //electron
        g.setColor(MyColor);
        g.drawOval(x,y,10,10);
        
        //panel
        g.setColor(Panel);
        g.fillRect(600,-1,900,600);
        
        //photon
        //g.setColor(Photon);
        //g.fillOval(px,py, 3, 3);
    }
    
    public void Collide(){
        if (x<minx) {
            xv=-xv;
        }
        if (x>maxx){
            xv=-xv;
        }
        if (y<miny) {
            yv=-yv;
        }
        if (y>maxy){
            yv=-yv;
        }
        x=x+xv;
        y=y+yv;
    }
    
    public void update(){
        for (int i=0;i<1000;i++){
            repaint();
            Collide();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VariablesPanel = new javax.swing.JPanel();
        playBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        comboPhi = new javax.swing.JComboBox();
        comboIntensity = new javax.swing.JComboBox();
        lblPhi = new javax.swing.JLabel();
        lblIntense = new javax.swing.JLabel();
        txtJoulesHf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblJoules = new javax.swing.JLabel();
        lblMeV = new javax.swing.JLabel();
        txtMeVHf = new javax.swing.JTextField();
        radioBtnJoules = new javax.swing.JRadioButton();
        radioBtnMeV = new javax.swing.JRadioButton();
        txtPhiJoules = new javax.swing.JLabel();
        txtPhiMeV = new javax.swing.JLabel();
        lblJoules1 = new javax.swing.JLabel();
        lblMeV1 = new javax.swing.JLabel();
        Test = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulation");

        playBtn.setText("Play");
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });

        comboPhi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Silver(Ag)", "Aluminium(Al)", "Gold(Au)", "Cesium(Cs)", "Copper(Cu)", "Lithium(Li)", "Lead(Pb)", "Tin(Sn)" }));

        comboIntensity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        lblPhi.setText("Material:");

        lblIntense.setText("Intensity:");

        txtJoulesHf.setText("50");
        txtJoulesHf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJoulesHfActionPerformed(evt);
            }
        });

        jLabel1.setText("Energy of Photon, hf:");

        lblJoules.setText("Joules");

        lblMeV.setText("MeV");

        txtMeVHf.setText("50");

        radioBtnJoules.setText("Joules");

        radioBtnMeV.setText("MeV");

        txtPhiJoules.setText("0");

        txtPhiMeV.setText("0");

        lblJoules1.setText("Joules");

        lblMeV1.setText("MeV");

        Test.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhi)
                            .addComponent(comboIntensity, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIntense, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtMeVHf, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMeV))
                            .addComponent(radioBtnMeV)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtJoulesHf, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblJoules))
                            .addComponent(radioBtnJoules)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(comboPhi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPhiJoules)
                                        .addComponent(txtPhiMeV))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblMeV1)
                                        .addComponent(lblJoules1))))
                            .addComponent(Test))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblPhi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhiJoules)
                    .addComponent(lblJoules1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhiMeV)
                    .addComponent(lblMeV1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBtnJoules)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJoulesHf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJoules))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnMeV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMeVHf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMeV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIntense)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboIntensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Test)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout VariablesPanelLayout = new javax.swing.GroupLayout(VariablesPanel);
        VariablesPanel.setLayout(VariablesPanelLayout);
        VariablesPanelLayout.setHorizontalGroup(
            VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VariablesPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playBtn)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        VariablesPanelLayout.setVerticalGroup(
            VariablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VariablesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playBtn)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(VariablesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VariablesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
        ChooseMetalString();
        Test.setText(material);
        
        if (radioBtnJoules.isSelected() || radioBtnMeV.isSelected()){
            
            switch (material){
                case "Silver(Ag)":
                    phiMeV  = 4.26f; // break used to avoid going through the rest of the switch statement if a match is found
                    phiJoules = 6.816*(10^-19);
                    
                    DisplayM = String.format("%.3g%n", phiMeV); //rounds up number to 3sf
                    txtPhiMeV.setText(DisplayM);
                    
                    break;
                case "Aluminium(Al)":
                    phiMeV = 4.28f;
                    
                    DisplayM = String.format("%.3g%n", phiMeV);
                    txtPhiMeV.setText(DisplayM);
                    
                    break;
                case "Gold(Au)":
                    phiMeV = 5.1f; 
                    
                    DisplayM = String.format("%.3g%n", phiMeV);
                    txtPhiMeV.setText(DisplayM);
                    
                    break;
                case "Cesium(Cs)":
                    phiMeV = 2.14f; 
                    
                    DisplayM = String.format("%.3g%n", phiMeV);
                    txtPhiMeV.setText(DisplayM);
                    
                    break;
                case "Copper(Cu)":
                    phiMeV = 4.65f; 
                    
                    DisplayM = String.format("%.3g%n", phiMeV);
                    txtPhiMeV.setText(DisplayM);
                    
                    break;
                case "Lithium(Li)":
                    phiMeV = 2.9f; 
                    
                    DisplayM = String.format("%.3g%n", phiMeV);
                    txtPhiMeV.setText(DisplayM);
                    
                    break;
                case "Lead(Pb)":
                    phiMeV = 4.25f; 
                    
                    DisplayM = String.format("%.3g%n", phiMeV);
                    txtPhiMeV.setText(DisplayM);
                    
                    break;
                case "Tin(Sn)":
                    phiMeV = 4.42f; 
                    
                    DisplayM = String.format("%.3g%n", phiMeV);
                    txtPhiMeV.setText(DisplayM);
                    
                    break;
            }
            
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(null, "Please Select Joules or MeV");
        }
        
        update();
              
    }//GEN-LAST:event_playBtnActionPerformed

    private void txtJoulesHfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJoulesHfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJoulesHfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simul2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Test;
    private javax.swing.JPanel VariablesPanel;
    private javax.swing.JComboBox comboIntensity;
    private javax.swing.JComboBox comboPhi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIntense;
    private javax.swing.JLabel lblJoules;
    private javax.swing.JLabel lblJoules1;
    private javax.swing.JLabel lblMeV;
    private javax.swing.JLabel lblMeV1;
    private javax.swing.JLabel lblPhi;
    private javax.swing.JButton playBtn;
    private javax.swing.JRadioButton radioBtnJoules;
    private javax.swing.JRadioButton radioBtnMeV;
    private javax.swing.JTextField txtJoulesHf;
    private javax.swing.JTextField txtMeVHf;
    private javax.swing.JLabel txtPhiJoules;
    private javax.swing.JLabel txtPhiMeV;
    // End of variables declaration//GEN-END:variables
}
